import type { Metadata } from 'next';
import { Container, Typography, Box, Link as MuiLink } from '@mui/material';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy | RxSynapse',
  description: 'Privacy Policy for RxSynapse and RxFlow - Learn how we collect, use, and protect your data',
};

export default function PrivacyPage() {
  return (
    <Box sx={{ bgcolor: '#0a0a0a', minHeight: '100vh', py: 8 }}>
      <Container maxWidth="md">
        {/* Header */}
        <Box sx={{ mb: 6 }}>
          <Link href="/" style={{ color: '#60a5fa', textDecoration: 'none' }}>
            ← Back to Home
          </Link>
          <Typography variant="h2" component="h1" sx={{ mt: 3, mb: 2, color: 'white', fontWeight: 'bold' }}>
            Privacy Policy
          </Typography>
          <Typography variant="body1" sx={{ color: '#9ca3af' }}>
            Last Updated: May 10, 2026
          </Typography>
        </Box>

        {/* Content */}
        <Box sx={{ color: '#d1d5db', '& h2': { color: 'white', mt: 6, mb: 3, fontSize: '1.875rem', fontWeight: 'bold' }, '& h3': { color: 'white', mt: 4, mb: 2, fontSize: '1.5rem', fontWeight: 'semibold' }, '& p': { mb: 2, lineHeight: 1.7 }, '& ul': { mb: 3, pl: 4 }, '& li': { mb: 1.5 }, '& a': { color: '#60a5fa', '&:hover': { color: '#93c5fd' } }, '& strong': { color: 'white' } }}>

          {/* Introduction */}
          <Typography paragraph>
            RxFlow (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is operated by RxSynapse. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our real-time options intelligence platform and services.
          </Typography>
          <Typography paragraph>
            By using RxFlow, you agree to the collection and use of information in accordance with this policy. If you do not agree with our policies and practices, please do not use our services.
          </Typography>

          {/* Information We Collect */}
          <Typography variant="h2" component="h2">
            1. Information We Collect
          </Typography>

          <Typography variant="h3" component="h3">
            1.1 Account Information
          </Typography>
          <Box component="ul">
            <li><strong>Phone Number:</strong> Required for authentication and account identification (E.164 format)</li>
            <li><strong>Name:</strong> User-editable display name</li>
            <li><strong>Email:</strong> Optional field reserved for future communication features</li>
            <li><strong>Firebase UID:</strong> Generated by Firebase Authentication for phone verification</li>
          </Box>

          <Typography variant="h3" component="h3">
            1.2 Telegram Integration Data
          </Typography>
          <Box component="ul">
            <li><strong>Telegram Chat ID:</strong> For delivering alerts via Telegram</li>
            <li><strong>Telegram Username:</strong> Your Telegram handle</li>
            <li><strong>Linking Token:</strong> One-time token with 10-minute expiry for account linking</li>
          </Box>

          <Typography variant="h3" component="h3">
            1.3 User Preferences and Settings
          </Typography>
          <Box component="ul">
            <li><strong>Alert Delivery Methods:</strong> Selected channels (Push, Email, Telegram, SMS)</li>
            <li><strong>Watchlist:</strong> Default and custom watchlists (symbols, strikes, option types)</li>
            <li><strong>Alert Severity Preference:</strong> LOW, MEDIUM, HIGH, or EXTREME</li>
            <li><strong>Trading Hours Setting:</strong> Whether to limit alerts to trading hours</li>
          </Box>

          <Typography variant="h3" component="h3">
            1.4 Usage and Engagement Data
          </Typography>
          <Box component="ul">
            <li><strong>Alert Quota Tracking:</strong> Daily quota usage per severity level</li>
            <li><strong>Alert History:</strong> Total alerts sent, missed, and delivery timestamps</li>
            <li><strong>Alert Outcomes:</strong> Performance tracking at 15min, 30min, 1hr, and 1-day intervals</li>
            <li><strong>Engagement Metrics:</strong> First alert date, last alert date, quota depletion events</li>
          </Box>

          <Typography variant="h3" component="h3">
            1.5 Payment Information
          </Typography>
          <Box component="ul">
            <li><strong>Order Details:</strong> Order ID, amount, currency (INR), plan type</li>
            <li><strong>Payment Method:</strong> Telegram Stars, Razorpay, or manual</li>
            <li><strong>Payment Status:</strong> Pending, success, failed, or refunded</li>
            <li><strong>Razorpay Data:</strong> Order ID, payment ID, signature, payment details (card/UPI metadata)</li>
            <li><strong>GST Information:</strong> GST breakdown (CGST, SGST, IGST), GSTIN</li>
            <li><strong>Device Information:</strong> IP address and user agent (browser/device) at payment time</li>
          </Box>

          <Typography variant="h3" component="h3">
            1.6 Analytics Data
          </Typography>
          <Box component="ul">
            <li><strong>Google Analytics 4 Events:</strong> Alert views, filters applied, subscriptions, stream controls</li>
            <li><strong>Page Views:</strong> Navigation patterns and feature usage</li>
            <li><strong>User Behavior:</strong> Engagement metrics and conversion events</li>
            <li><strong>Location:</strong> General location information collected by Google Analytics (not precise geolocation)</li>
          </Box>

          <Typography variant="h3" component="h3">
            1.7 Feedback Data
          </Typography>
          <Box component="ul">
            <li><strong>Daily Feedback:</strong> Helpful/not helpful ratings and optional comments</li>
            <li><strong>Tickets:</strong> Feature requests and bug reports with voting and comments</li>
          </Box>

          {/* How We Use Information */}
          <Typography variant="h2" component="h2">
            2. How We Use Your Information
          </Typography>
          <Typography paragraph>
            We use the collected information for the following purposes:
          </Typography>
          <Box component="ul">
            <li><strong>Service Delivery:</strong> Deliver real-time market alerts via Telegram based on your preferences</li>
            <li><strong>Authentication:</strong> Verify your identity and manage your account</li>
            <li><strong>Payment Processing:</strong> Process subscriptions and manage billing</li>
            <li><strong>Performance Tracking:</strong> Track alert outcomes to measure and display success rates</li>
            <li><strong>Personalization:</strong> Customize alert delivery based on your watchlist and severity preferences</li>
            <li><strong>Analytics:</strong> Improve our detection algorithms and product features</li>
            <li><strong>Communication:</strong> Send daily summaries, quota notifications, and service updates</li>
            <li><strong>Support:</strong> Respond to your feedback, feature requests, and support tickets</li>
            <li><strong>Compliance:</strong> Fulfill legal obligations including GST compliance and tax reporting</li>
          </Box>

          {/* Third-Party Services */}
          <Typography variant="h2" component="h2">
            3. Third-Party Services
          </Typography>
          <Typography paragraph>
            We integrate with the following third-party services to provide our platform:
          </Typography>

          <Typography variant="h3" component="h3">
            3.1 Firebase Authentication (Google)
          </Typography>
          <Box component="ul">
            <li><strong>Purpose:</strong> Phone number verification and authentication</li>
            <li><strong>Data Shared:</strong> Phone number, Firebase UID</li>
            <li><strong>Privacy Policy:</strong> <MuiLink href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener noreferrer">Firebase Privacy Policy</MuiLink></li>
          </Box>

          <Typography variant="h3" component="h3">
            3.2 Razorpay (Payment Gateway)
          </Typography>
          <Box component="ul">
            <li><strong>Purpose:</strong> Process credit card, UPI, and other payment methods</li>
            <li><strong>Data Shared:</strong> Order amount, user contact information, IP address, device information</li>
            <li><strong>Note:</strong> Razorpay handles PCI-DSS compliant payment processing. We do not store credit card numbers.</li>
            <li><strong>Privacy Policy:</strong> <MuiLink href="https://razorpay.com/privacy/" target="_blank" rel="noopener noreferrer">Razorpay Privacy Policy</MuiLink></li>
          </Box>

          <Typography variant="h3" component="h3">
            3.3 Telegram Bot API
          </Typography>
          <Box component="ul">
            <li><strong>Purpose:</strong> Deliver real-time alerts and subscription management</li>
            <li><strong>Data Shared:</strong> Telegram Chat ID, username, alert messages</li>
            <li><strong>Privacy Policy:</strong> <MuiLink href="https://telegram.org/privacy" target="_blank" rel="noopener noreferrer">Telegram Privacy Policy</MuiLink></li>
          </Box>

          <Typography variant="h3" component="h3">
            3.4 Angel One SmartAPI
          </Typography>
          <Box component="ul">
            <li><strong>Purpose:</strong> Real-time options market data streaming</li>
            <li><strong>Data Shared:</strong> No personal user data is sent to Angel One</li>
            <li><strong>Note:</strong> We only consume public market data; we do not share your account information</li>
          </Box>

          <Typography variant="h3" component="h3">
            3.5 Google Analytics 4
          </Typography>
          <Box component="ul">
            <li><strong>Purpose:</strong> Track user engagement, feature usage, and conversion events</li>
            <li><strong>Data Shared:</strong> Page views, custom events, general location information</li>
            <li><strong>Opt-Out:</strong> You can opt out by disabling analytics in your browser or using Google Analytics Opt-out Browser Add-on</li>
            <li><strong>Privacy Policy:</strong> <MuiLink href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</MuiLink></li>
          </Box>

          {/* Data Storage and Security */}
          <Typography variant="h2" component="h2">
            4. Data Storage and Security
          </Typography>

          <Typography variant="h3" component="h3">
            4.1 Data Storage
          </Typography>
          <Box component="ul">
            <li><strong>Primary Database:</strong> PostgreSQL hosted on Railway with SSL/TLS encryption</li>
            <li><strong>Cache:</strong> Redis for temporary data and job queues</li>
            <li><strong>Location:</strong> Data centers in secure, compliant facilities</li>
          </Box>

          <Typography variant="h3" component="h3">
            4.2 Security Measures
          </Typography>
          <Box component="ul">
            <li><strong>Encryption:</strong> All data transmitted over HTTPS/TLS</li>
            <li><strong>Authentication:</strong> JWT tokens with secure secret keys</li>
            <li><strong>Password Security:</strong> bcryptjs hashing for password storage (when applicable)</li>
            <li><strong>Access Control:</strong> Role-based access control and authentication middleware</li>
            <li><strong>API Security:</strong> Rate limiting and CORS protection</li>
          </Box>

          <Typography variant="h3" component="h3">
            4.3 Data Retention
          </Typography>
          <Box component="ul">
            <li><strong>Account Data:</strong> Retained until account deletion</li>
            <li><strong>Payment Records:</strong> Retained for 7 years for tax and legal compliance</li>
            <li><strong>Alert History:</strong> Retained for performance tracking and analytics</li>
            <li><strong>Analytics Data:</strong> Retained per Google Analytics 4 data retention settings (default: 14 months)</li>
          </Box>

          {/* Your Rights */}
          <Typography variant="h2" component="h2">
            5. Your Rights and Choices
          </Typography>

          <Typography variant="h3" component="h3">
            5.1 Access and Update
          </Typography>
          <Typography paragraph>
            You have the right to:
          </Typography>
          <Box component="ul">
            <li>Access your personal data stored in our system</li>
            <li>Update your account information, preferences, and watchlists</li>
            <li>Request a copy of your data</li>
          </Box>

          <Typography variant="h3" component="h3">
            5.2 Account Deletion
          </Typography>
          <Box component="ul">
            <li>You can delete your account at any time through the profile settings</li>
            <li>Upon deletion, all related data (preferences, alerts, triggers, moments) will be permanently removed</li>
            <li>Payment records may be retained for legal compliance (7 years)</li>
            <li>Deletion is irreversible and cannot be undone</li>
          </Box>

          <Typography variant="h3" component="h3">
            5.3 Alert Preferences
          </Typography>
          <Box component="ul">
            <li>Customize alert severity levels (LOW, MEDIUM, HIGH, EXTREME)</li>
            <li>Modify watchlists and trading hours settings</li>
            <li>Unlink Telegram account at any time</li>
          </Box>

          <Typography variant="h3" component="h3">
            5.4 Analytics Opt-Out
          </Typography>
          <Typography paragraph>
            To opt out of Google Analytics tracking, you can:
          </Typography>
          <Box component="ul">
            <li>Use the Google Analytics Opt-out Browser Add-on</li>
            <li>Enable Do Not Track (DNT) in your browser settings</li>
            <li>Use ad-blocking or privacy-focused browser extensions</li>
          </Box>

          {/* Data Sharing */}
          <Typography variant="h2" component="h2">
            6. Data Sharing and Disclosure
          </Typography>
          <Typography paragraph>
            We do not sell, trade, or rent your personal information to third parties. We may share data only in the following circumstances:
          </Typography>
          <Box component="ul">
            <li><strong>Service Providers:</strong> Firebase, Razorpay, Telegram, and Google Analytics as described in Section 3</li>
            <li><strong>Legal Compliance:</strong> When required by law, court order, or government regulation</li>
            <li><strong>Business Transfers:</strong> In the event of a merger, acquisition, or sale of assets</li>
            <li><strong>Protection:</strong> To protect the rights, property, or safety of RxFlow, our users, or the public</li>
          </Box>

          {/* Children's Privacy */}
          <Typography variant="h2" component="h2">
            7. Children&apos;s Privacy
          </Typography>
          <Typography paragraph>
            RxFlow is not intended for users under the age of 18. We do not knowingly collect personal information from children. If you believe we have inadvertently collected information from a child, please contact us immediately.
          </Typography>

          {/* International Users */}
          <Typography variant="h2" component="h2">
            8. International Users
          </Typography>
          <Typography paragraph>
            RxFlow is designed for the Indian market and operates in compliance with Indian laws. If you access our services from outside India, you acknowledge that your data may be transferred to and processed in India.
          </Typography>

          {/* Cookies and Tracking */}
          <Typography variant="h2" component="h2">
            9. Cookies and Tracking Technologies
          </Typography>
          <Typography paragraph>
            We use the following technologies:
          </Typography>
          <Box component="ul">
            <li><strong>Local Storage:</strong> To store authentication tokens and user preferences in your browser</li>
            <li><strong>Cookies:</strong> Google Analytics uses cookies to track user behavior and engagement</li>
            <li><strong>Session Tokens:</strong> JWT tokens for authenticated API requests</li>
          </Box>
          <Typography paragraph>
            You can disable cookies through your browser settings, but this may affect the functionality of our platform.
          </Typography>

          {/* Changes to Privacy Policy */}
          <Typography variant="h2" component="h2">
            10. Changes to This Privacy Policy
          </Typography>
          <Typography paragraph>
            We may update this Privacy Policy from time to time. The &quot;Last Updated&quot; date at the top of this page indicates when the policy was last revised. We will notify you of material changes via:
          </Typography>
          <Box component="ul">
            <li>Email notification (if email is provided)</li>
            <li>Telegram bot notification</li>
            <li>Prominent notice on our website</li>
          </Box>
          <Typography paragraph>
            Your continued use of RxFlow after changes are posted constitutes acceptance of the updated policy.
          </Typography>

          {/* Contact */}
          <Typography variant="h2" component="h2">
            11. Contact Us
          </Typography>
          <Typography paragraph>
            If you have questions, concerns, or requests regarding this Privacy Policy or your personal data, please contact us:
          </Typography>
          <Box component="ul" sx={{ listStyle: 'none', pl: 0 }}>
            <li><strong>Email:</strong> support@rxsynapse.com</li>
            <li><strong>Telegram:</strong> <MuiLink href="https://t.me/rxflow_alerts_bot" target="_blank" rel="noopener noreferrer">@rxflow_alerts_bot</MuiLink></li>
            <li><strong>Company:</strong> RxSynapse</li>
            <li><strong>Website:</strong> <MuiLink href="https://flow.rxsynapse.com" target="_blank" rel="noopener noreferrer">https://flow.rxsynapse.com</MuiLink></li>
          </Box>

          {/* Legal Framework */}
          <Typography variant="h2" component="h2">
            12. Legal Framework
          </Typography>
          <Typography paragraph>
            This Privacy Policy is governed by the laws of India. We comply with:
          </Typography>
          <Box component="ul">
            <li><strong>Information Technology Act, 2000</strong> and its amendments</li>
            <li><strong>Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011</strong></li>
            <li><strong>Digital Personal Data Protection Act, 2023</strong> (when applicable)</li>
            <li><strong>GST regulations</strong> for payment processing and tax compliance</li>
          </Box>

          {/* Consent */}
          <Box sx={{ bgcolor: '#1e3a8a20', border: '1px solid #1e3a8a', borderRadius: 2, p: 3, mt: 6 }}>
            <Typography variant="h2" component="h2" sx={{ mt: 0 }}>
              Your Consent
            </Typography>
            <Typography paragraph sx={{ mb: 0 }}>
              By using RxFlow, you consent to this Privacy Policy and agree to its terms. If you do not agree with this policy, please discontinue use of our services immediately.
            </Typography>
          </Box>
        </Box>
      </Container>
    </Box>
  );
}
